### Create tenant
POST http://localhost:3000/tenants
Content-Type: application/json

{ "name": "Test Company" }

###

### Get all tenants
GET http://localhost:3000/tenants

### health check
GET http://localhost:3000/health

### Get metrics
GET http://localhost:3000/metrics

### Create Document
POST http://localhost:3000/documents
Content-Type: application/json

{
  "title": "File Upload Test",
  "tenantId": "49f8fb0b-4e41-4293-8f4e-dfbe70bade41",
  "sourceType": "upload"
}


### Get documents from tenantId
GET http://localhost:3000/documents/49f8fb0b-4e41-4293-8f4e-dfbe70bade41


### Ingest document
POST http://localhost:3000/ingestion/ingest
Content-Type: application/json

{
  "documentId": "69d7c9ae-efd7-416e-8a33-3b785e71bd3b",
  "tenantId": "49f8fb0b-4e41-4293-8f4e-dfbe70bade41",
  "content": "NestJS is a framework for building efficient, scalable Node.js server-side applications. It uses TypeScript by default and combines elements of OOP, FP, and FRP. NestJS is built around the concept of modules, controllers, and providers. Modules are the basic building blocks of a NestJS application. Controllers handle incoming requests and return responses to the client. Providers are the main source of business logic in NestJS. Services are a type of provider that can be injected into controllers and other services."
}

### Semantic search
POST http://localhost:3000/rag/search
Content-Type: application/json

{
  "query": "what are the building blocks of NestJS?",
  "tenantId": "49f8fb0b-4e41-4293-8f4e-dfbe70bade41",
  "limit": 5
}

### RAG Q&A
POST http://localhost:3000/rag/ask
Content-Type: application/json

{
  "question": "What are the building blocks of NestJS?",
  "tenantId": "49f8fb0b-4e41-4293-8f4e-dfbe70bade41"
}