### Create tenant
POST http://localhost:3000/tenants
Content-Type: application/json

{ "name": "Test Company" }

###

### Get all tenants
GET http://localhost:3000/tenants

### health check
GET http://localhost:3000/health

### Get metrics
GET http://localhost:3000/metrics